<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.9.1" xml:lang="fr">
  <compounddef id="classseine__data__utils__py_1_1_frontiere_1_1_hors_de_la_frontiere_error" kind="class" language="Python" prot="public">
    <compoundname>seine_data_utils_py::Frontiere::HorsDeLaFrontiereError</compoundname>
    <basecompoundref prot="public" virt="non-virtual">Exception</basecompoundref>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="1">
        <label>seine_data_utils_py.Frontiere.HorsDeLaFrontiereError</label>
        <link refid="classseine__data__utils__py_1_1_frontiere_1_1_hors_de_la_frontiere_error"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>Exception</label>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="1">
        <label>seine_data_utils_py.Frontiere.HorsDeLaFrontiereError</label>
        <link refid="classseine__data__utils__py_1_1_frontiere_1_1_hors_de_la_frontiere_error"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>Exception</label>
      </node>
    </collaborationgraph>
    <location file="src/clusterizer/utils/seine_data_utils_py.py" line="165" column="1" bodyfile="src/clusterizer/utils/seine_data_utils_py.py" bodystart="165" bodyend="166"/>
    <listofallmembers>
    </listofallmembers>
  </compounddef>
</doxygen>
